version: '3.1'

services:

  web:
    build: ..
    ports:
      - 5001:80 
      - 5002:443
    env_file:
      - .env
    networks:
      - dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: totallywired
      POSTGRES_PASSWORD: strongpassword!
    ports:
      - 9999:5432 
    networks:
      - dev
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /data/db_data
      o: bind